// lib/features/progress/domain/entities/daily_activity.dart

class DailyActivity {
  final String id;
  final String titleEn;
  final String titleAr;
  final String descriptionEn;
  final String descriptionAr;
  final String category; // morning, afternoon, evening
  final int estimatedMinutes;
  final List<String> tags; // mental_health, mindfulness, self_care, etc.

  DailyActivity({
    required this.id,
    required this.titleEn,
    required this.titleAr,
    required this.descriptionEn,
    required this.descriptionAr,
    required this.category,
    required this.estimatedMinutes,
    required this.tags,
  });

  factory DailyActivity.fromMap(Map<String, dynamic> map) {
    return DailyActivity(
      id: map['id'],
      titleEn: map['titleEn'],
      titleAr: map['titleAr'],
      descriptionEn: map['descriptionEn'],
      descriptionAr: map['descriptionAr'],
      category: map['category'],
      estimatedMinutes: map['estimatedMinutes'],
      tags: List<String>.from(map['tags']),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'titleEn': titleEn,
      'titleAr': titleAr,
      'descriptionEn': descriptionEn,
      'descriptionAr': descriptionAr,
      'category': category,
      'estimatedMinutes': estimatedMinutes,
      'tags': tags,
    };
  }
}

// Activity Repository
class DailyActivityRepository {
  List<DailyActivity> getAllActivities() {
    return _allActivities;
  }

  List<DailyActivity> getActivitiesByCategory(String category) {
    return _allActivities.where((activity) => activity.category == category).toList();
  }

  List<DailyActivity> getActivitiesByTags(List<String> tags) {
    return _allActivities.where((activity) =>
        activity.tags.any((tag) => tags.contains(tag))
    ).toList();
  }

  DailyActivity? getActivityById(String id) {
    return _allActivities.firstWhere((activity) => activity.id == id);
  }

  // Get 3 random activities for today (one from each category)
  List<DailyActivity> getTodaysActivities() {
    final morningActivities = getActivitiesByCategory('morning');
    final afternoonActivities = getActivitiesByCategory('afternoon');
    final eveningActivities = getActivitiesByCategory('evening');

    final random = DateTime.now().microsecondsSinceEpoch;

    return [
      morningActivities[(random % morningActivities.length).toInt()],
      afternoonActivities[(random % afternoonActivities.length).toInt()],
      eveningActivities[(random % eveningActivities.length).toInt()],
    ];
  }

  // List of all activities
  static final List<DailyActivity> _allActivities = [
    // Morning Activities (16)
    DailyActivity(
      id: 'morning_gratitude',
      titleEn: 'Morning Gratitude',
      titleAr: 'شكر الصباح',
      descriptionEn: 'Write down 3 things you\'re grateful for today',
      descriptionAr: 'اكتب ثلاثة أشياء تشعر بالامتنان لها اليوم',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['mindfulness', 'gratitude', 'positive_thinking'],
    ),
    DailyActivity(
      id: 'deep_breathing',
      titleEn: 'Deep Breathing',
      titleAr: 'التنفس العميق',
      descriptionEn: 'Take 10 deep breaths, inhaling for 4 seconds, holding for 4, exhaling for 6',
      descriptionAr: 'خذ 10 أنفاس عميقة: شهيق 4 ثوانٍ، حبس النفس 4 ثوانٍ، زفير 6 ثوانٍ',
      category: 'morning',
      estimatedMinutes: 3,
      tags: ['mindfulness', 'stress_relief', 'breathing'],
    ),
    DailyActivity(
      id: 'intention_setting',
      titleEn: 'Intention Setting',
      titleAr: 'تحديد النوايا',
      descriptionEn: 'Set one positive intention for your day',
      descriptionAr: 'حدد نية واحدة إيجابية ليومك',
      category: 'morning',
      estimatedMinutes: 2,
      tags: ['mindfulness', 'focus', 'positive_thinking'],
    ),
    DailyActivity(
      id: 'sunlight_exposure',
      titleEn: 'Sunlight Exposure',
      titleAr: 'التعرض لأشعة الشمس',
      descriptionEn: 'Spend 5 minutes in morning sunlight',
      descriptionAr: 'اقضي 5 دقائق تحت أشعة الشمس الصباحية',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['physical_health', 'energy', 'vitamin_d'],
    ),
    DailyActivity(
      id: 'gentle_stretching',
      titleEn: 'Gentle Stretching',
      titleAr: 'تمارين التمدد اللطيفة',
      descriptionEn: 'Do 5 minutes of gentle full-body stretching',
      descriptionAr: 'قم بتمارين تمدد لطيفة للجسم كامل لمدة 5 دقائق',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['physical_health', 'flexibility', 'energy'],
    ),
    DailyActivity(
      id: 'mindful_tea',
      titleEn: 'Mindful Tea/Coffee',
      titleAr: 'شاي/قهوة واعية',
      descriptionEn: 'Drink your morning beverage mindfully, focusing on the senses',
      descriptionAr: 'اشرب مشروبك الصباحي بانتباه، مركزًا على الحواس',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['mindfulness', 'sensory_awareness'],
    ),
    DailyActivity(
      id: 'positive_affirmation',
      titleEn: 'Positive Affirmation',
      titleAr: 'توكيد إيجابي',
      descriptionEn: 'Repeat a positive affirmation 3 times',
      descriptionAr: 'كرر تأكيدًا إيجابيًا 3 مرات',
      category: 'morning',
      estimatedMinutes: 2,
      tags: ['positive_thinking', 'self_esteem'],
    ),
    DailyActivity(
      id: 'journal_prompt',
      titleEn: 'Journal Prompt',
      titleAr: 'كتابة يومية',
      descriptionEn: 'Write about: "What would make today great?"',
      descriptionAr: 'اكتب عن: "ما الذي سيجعل اليوم رائعًا؟"',
      category: 'morning',
      estimatedMinutes: 7,
      tags: ['journaling', 'reflection'],
    ),
    DailyActivity(
      id: 'mindful_shower',
      titleEn: 'Mindful Shower',
      titleAr: 'استحمام واعي',
      descriptionEn: 'Take a shower focusing on the sensations of water',
      descriptionAr: 'خذ حمامًا مركزًا على أحاسيس الماء',
      category: 'morning',
      estimatedMinutes: 10,
      tags: ['mindfulness', 'sensory_awareness'],
    ),
    DailyActivity(
      id: 'digital_detox_start',
      titleEn: 'Digital Detox Start',
      titleAr: 'بداية صيام رقمي',
      descriptionEn: 'Delay checking phone/email for first 30 minutes',
      descriptionAr: 'تأجيل التحقق من الهاتف/البريد الإلكتروني لأول 30 دقيقة',
      category: 'morning',
      estimatedMinutes: 1,
      tags: ['digital_detox', 'focus'],
    ),
    DailyActivity(
      id: 'nature_sounds',
      titleEn: 'Nature Sounds',
      titleAr: 'أصوات الطبيعة',
      descriptionEn: 'Listen to 5 minutes of nature sounds',
      descriptionAr: 'استمع إلى أصوات الطبيعة لمدة 5 دقائق',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['relaxation', 'nature'],
    ),
    DailyActivity(
      id: 'energy_visualization',
      titleEn: 'Energy Visualization',
      titleAr: 'تصور الطاقة',
      descriptionEn: 'Visualize positive energy filling your body',
      descriptionAr: 'تخيل طاقة إيجابية تملأ جسدك',
      category: 'morning',
      estimatedMinutes: 3,
      tags: ['visualization', 'energy'],
    ),
    DailyActivity(
      id: 'mindful_breakfast',
      titleEn: 'Mindful Breakfast',
      titleAr: 'فطور واعٍ',
      descriptionEn: 'Eat breakfast without distractions',
      descriptionAr: 'تناول الفطور دون مشتتات',
      category: 'morning',
      estimatedMinutes: 15,
      tags: ['mindful_eating', 'nutrition'],
    ),
    DailyActivity(
      id: 'body_scan',
      titleEn: 'Body Scan',
      titleAr: 'مسح الجسم',
      descriptionEn: 'Scan your body from head to toe, noticing sensations',
      descriptionAr: 'امسح جسدك من الرأس إلى القدمين، ملاحظًا الأحاسيس',
      category: 'morning',
      estimatedMinutes: 5,
      tags: ['body_awareness', 'mindfulness'],
    ),
    DailyActivity(
      id: 'scent_therapy',
      titleEn: 'Scent Therapy',
      titleAr: 'علاج بالعطور',
      descriptionEn: 'Smell a pleasant scent (essential oil, flower, citrus)',
      descriptionAr: 'شم رائحة جميلة (زيت عطري، زهرة، حمضيات)',
      category: 'morning',
      estimatedMinutes: 2,
      tags: ['sensory_awareness', 'aromatherapy'],
    ),
    DailyActivity(
      id: 'hydration_check',
      titleEn: 'Hydration Check',
      titleAr: 'فحص الترطيب',
      descriptionEn: 'Drink a full glass of water first thing',
      descriptionAr: 'اشرب كوبًا كاملًا من الماء أول شيء',
      category: 'morning',
      estimatedMinutes: 2,
      tags: ['physical_health', 'hydration'],
    ),

    // Afternoon Activities (17)
    DailyActivity(
      id: 'mindful_walk',
      titleEn: 'Mindful Walk',
      titleAr: 'مشية واعية',
      descriptionEn: 'Take a 10-minute walk focusing on your surroundings',
      descriptionAr: 'تمشى لمدة 10 دقائق مركزًا على محيطك',
      category: 'afternoon',
      estimatedMinutes: 10,
      tags: ['mindfulness', 'exercise', 'nature'],
    ),
    DailyActivity(
      id: 'desk_stretches',
      titleEn: 'Desk Stretches',
      titleAr: 'تمارين تمدد للمكتب',
      descriptionEn: 'Do 3 stretches if you\'ve been sitting',
      descriptionAr: 'قم بثلاثة تمارين تمدد إذا كنت جالسًا',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: ['physical_health', 'ergonomics'],
    ),
    DailyActivity(
      id: 'breathing_break',
      titleEn: 'Breathing Break',
      titleAr: 'استراحة تنفس',
      descriptionEn: 'Stop for 1 minute and focus on your breath',
      descriptionAr: 'توقف لمدة دقيقة وركز على أنفاسك',
      category: 'afternoon',
      estimatedMinutes: 1,
      tags: ['mindfulness', 'stress_relief'],
    ),
    DailyActivity(
      id: 'gratitude_moment',
      titleEn: 'Gratitude Moment',
      titleAr: 'لحظة امتنان',
      descriptionEn: 'Think of one good thing that happened today',
      descriptionAr: 'فكر في شيء جيد حدث اليوم',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: ['gratitude', 'positive_thinking'],
    ),
    DailyActivity(
      id: 'digital_detox_break',
      titleEn: 'Digital Detox Break',
      titleAr: 'استراحة صيام رقمي',
      descriptionEn: '15 minutes without screens',
      descriptionAr: '15 دقيقة بدون شاشات',
      category: 'afternoon',
      estimatedMinutes: 15,
      tags: ['digital_detox', 'eye_rest'],
    ),
    DailyActivity(
      id: 'hydrate_check',
      titleEn: 'Hydrate Check',
      titleAr: 'فحص الترطيب',
      descriptionEn: 'Drink a glass of water',
      descriptionAr: 'اشرب كوبًا من الماء',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: ['physical_health', 'hydration'],
    ),
    DailyActivity(
      id: 'mindful_snack',
      titleEn: 'Mindful Snack',
      titleAr: 'وجبة خفيفة واعية',
      descriptionEn: 'Eat a snack slowly, noticing flavors',
      descriptionAr: 'تناول وجبة خفيفة ببطء، ملاحظًا النكهات',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: ['mindful_eating', 'nutrition'],
    ),
    DailyActivity(
      id: 'nature_connection',
      titleEn: 'Nature Connection',
      titleAr: 'اتصال بالطبيعة',
      descriptionEn: 'Look at something natural (plant, sky, cloud)',
      descriptionAr: 'انظر إلى شيء طبيعي (نبات، سماء، سحابة)',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: ['nature', 'mindfulness'],
    ),
    DailyActivity(
      id: 'posture_check',
      titleEn: 'Posture Check',
      titleAr: 'فحص وضعية الجسم',
      descriptionEn: 'Adjust your posture to be more aligned',
      descriptionAr: 'اضبط وضعية جسمك لتكون أكثر استقامة',
      category: 'afternoon',
      estimatedMinutes: 1,
      tags: ['physical_health', 'posture'],
    ),
    DailyActivity(
      id: 'kindness_act',
      titleEn: 'Kindness Act',
      titleAr: 'فعل لطافة',
      descriptionEn: 'Do one small act of kindness',
      descriptionAr: 'قم بفعل لطافة صغير واحد',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: ['kindness', 'compassion'],
    ),
    DailyActivity(
      id: 'music_break',
      titleEn: 'Music Break',
      titleAr: 'استراحة موسيقية',
      descriptionEn: 'Listen to one calming song',
      descriptionAr: 'استمع إلى أغنية هادئة واحدة',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: ['music', 'relaxation'],
    ),
    DailyActivity(
      id: 'tension_release',
      titleEn: 'Tension Release',
      titleAr: 'تحرير التوتر',
      descriptionEn: 'Shake out tension from shoulders and neck',
      descriptionAr: 'اهز التوتر من الكتفين والرقبة',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: ['stress_relief', 'physical_health'],
    ),
    DailyActivity(
      id: 'mindful_hand_washing',
      titleEn: 'Mindful Hand Washing',
      titleAr: 'غسل اليدين الواعي',
      descriptionEn: 'Wash hands slowly, feeling the water and soap',
      descriptionAr: 'اغسل يديك ببطء، محسًا بالماء والصابون',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: ['mindfulness', 'sensory_awareness'],
    ),
    DailyActivity(
      id: 'positive_interaction',
      titleEn: 'Positive Interaction',
      titleAr: 'تفاعل إيجابي',
      descriptionEn: 'Have one positive conversation',
      descriptionAr: 'أجر محادثة إيجابية واحدة',
      category: 'afternoon',
      estimatedMinutes: 10,
      tags: ['social', 'communication'],
    ),
    DailyActivity(
      id: 'task_prioritization',
      titleEn: 'Task Prioritization',
      titleAr: 'ترتيب أولويات المهام',
      descriptionEn: 'Review and prioritize remaining tasks',
      descriptionAr: 'راجع ورتب أولويات المهام المتبقية',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: ['productivity', 'organization'],
    ),
    DailyActivity(
      id: 'eye_relaxation',
      titleEn: 'Eye Relaxation',
      titleAr: 'استرخاء العينين',
      descriptionEn: 'Practice the 20-20-20 rule (look 20 feet away for 20 seconds)',
      descriptionAr: 'مارس قاعدة 20-20-20 (انظر إلى بعد 20 قدمًا لمدة 20 ثانية)',
      category: 'afternoon',
      estimatedMinutes: 1,
      tags: ['eye_health', 'digital_detox'],
    ),
    DailyActivity(
      id: 'temperature_change',
      titleEn: 'Temperature Change',
      titleAr: 'تغيير درجة الحرارة',
      descriptionEn: 'Splash cold water on face or step outside for air',
      descriptionAr: 'رش ماء بارد على الوجه أو اخرج للهواء',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: ['energy_boost', 'sensory_awareness'],
    ),

    // Evening Activities (17)
    DailyActivity(
      id: 'evening_gratitude',
      titleEn: 'Evening Gratitude',
      titleAr: 'امتنان المساء',
      descriptionEn: 'Write 3 good things from today',
      descriptionAr: 'اكتب ثلاثة أشياء جيدة من اليوم',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['gratitude', 'journaling', 'reflection'],
    ),
    DailyActivity(
      id: 'digital_sunset',
      titleEn: 'Digital Sunset',
      titleAr: 'غروب رقمي',
      descriptionEn: 'Turn off screens 1 hour before bed',
      descriptionAr: 'أطفئ الشاشات قبل النوم بساعة',
      category: 'evening',
      estimatedMinutes: 1,
      tags: ['digital_detox', 'sleep_hygiene'],
    ),
    DailyActivity(
      id: 'gentle_yoga',
      titleEn: 'Gentle Yoga',
      titleAr: 'يوغا لطيفة',
      descriptionEn: '5 minutes of gentle evening yoga/stretching',
      descriptionAr: '5 دقائق من اليوغا/التمدد المسائية اللطيفة',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['physical_health', 'relaxation'],
    ),
    DailyActivity(
      id: 'breathing_for_sleep',
      titleEn: 'Breathing for Sleep',
      titleAr: 'تنفس للنوم',
      descriptionEn: 'Practice 4-7-8 breathing (inhale 4, hold 7, exhale 8)',
      descriptionAr: 'مارس تنفس 4-7-8 (شهيق 4، حبس 7، زفير 8)',
      category: 'evening',
      estimatedMinutes: 3,
      tags: ['breathing', 'sleep_hygiene'],
    ),
    DailyActivity(
      id: 'mindful_tea_evening',
      titleEn: 'Mindful Herbal Tea',
      titleAr: 'شاي أعشاب واعٍ',
      descriptionEn: 'Drink caffeine-free tea mindfully',
      descriptionAr: 'اشرب شايًا خاليًا من الكافيين بانتباه',
      category: 'evening',
      estimatedMinutes: 10,
      tags: ['mindfulness', 'relaxation'],
    ),
    DailyActivity(
      id: 'evening_journal',
      titleEn: 'Evening Reflection',
      titleAr: 'تأمل مسائي',
      descriptionEn: 'Journal about: "What did I learn today?"',
      descriptionAr: 'اكتب في اليومية: "ماذا تعلمت اليوم؟"',
      category: 'evening',
      estimatedMinutes: 7,
      tags: ['journaling', 'reflection'],
    ),
    DailyActivity(
      id: 'body_scan_evening',
      titleEn: 'Evening Body Scan',
      titleAr: 'مسح الجسم المسائي',
      descriptionEn: 'Scan body for tension and consciously relax',
      descriptionAr: 'امسح الجسم بحثًا عن التوتر واسترخي بوعي',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['body_awareness', 'relaxation'],
    ),
    DailyActivity(
      id: 'gratitude_meditation',
      titleEn: 'Gratitude Meditation',
      titleAr: 'تأمل الامتنان',
      descriptionEn: '5-minute gratitude meditation',
      descriptionAr: 'تأمل امتنان لمدة 5 دقائق',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['meditation', 'gratitude'],
    ),
    DailyActivity(
      id: 'prep_tomorrow',
      titleEn: 'Prepare for Tomorrow',
      titleAr: 'الاستعداد للغد',
      descriptionEn: 'Set out clothes/items for tomorrow',
      descriptionAr: 'جهز الملابس/الأشياء للغد',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['organization', 'productivity'],
    ),
    DailyActivity(
      id: 'positive_review',
      titleEn: 'Positive Review',
      titleAr: 'مراجعة إيجابية',
      descriptionEn: 'Recall one success or accomplishment from today',
      descriptionAr: 'تذكر نجاحًا أو إنجازًا واحدًا من اليوم',
      category: 'evening',
      estimatedMinutes: 3,
      tags: ['positive_thinking', 'self_esteem'],
    ),
    DailyActivity(
      id: 'reading_time',
      titleEn: 'Reading Time',
      titleAr: 'وقت القراءة',
      descriptionEn: 'Read something relaxing (not on screen)',
      descriptionAr: 'اقرأ شيئًا مريحًا (ليس على الشاشة)',
      category: 'evening',
      estimatedMinutes: 15,
      tags: ['relaxation', 'learning'],
    ),
    DailyActivity(
      id: 'calming_music',
      titleEn: 'Calming Music',
      titleAr: 'موسيقى مهدئة',
      descriptionEn: 'Listen to calming instrumental music',
      descriptionAr: 'استمع إلى موسيقى آلية مهدئة',
      category: 'evening',
      estimatedMinutes: 10,
      tags: ['music', 'relaxation'],
    ),
    DailyActivity(
      id: 'aromatherapy_evening',
      titleEn: 'Evening Aromatherapy',
      titleAr: 'علاج عطري مسائي',
      descriptionEn: 'Use calming scents (lavender, chamomile)',
      descriptionAr: 'استخدم روائح مهدئة (خزامى، بابونج)',
      category: 'evening',
      estimatedMinutes: 3,
      tags: ['aromatherapy', 'relaxation'],
    ),
    DailyActivity(
      id: 'temperature_adjustment',
      titleEn: 'Sleep Temperature',
      titleAr: 'درجة حرارة النوم',
      descriptionEn: 'Adjust room temperature for optimal sleep',
      descriptionAr: 'اضبط درجة حرارة الغرفة للنوم الأمثل',
      category: 'evening',
      estimatedMinutes: 2,
      tags: ['sleep_hygiene', 'environment'],
    ),
    DailyActivity(
      id: 'mindful_brushing',
      titleEn: 'Mindful Teeth Brushing',
      titleAr: 'تفريش الأسنان الواعي',
      descriptionEn: 'Brush teeth slowly and mindfully',
      descriptionAr: 'فرش أسنانك ببطء ووعي',
      category: 'evening',
      estimatedMinutes: 3,
      tags: ['mindfulness', 'hygiene'],
    ),
    DailyActivity(
      id: 'let_go_ritual',
      titleEn: 'Letting Go Ritual',
      titleAr: 'طقوس التخلي',
      descriptionEn: 'Write down one worry and "release" it',
      descriptionAr: 'اكتب همًا واحدًا و"أطلقه"',
      category: 'evening',
      estimatedMinutes: 5,
      tags: ['stress_relief', 'emotional_release'],
    ),
    DailyActivity(
      id: 'bedtime_affirmation',
      titleEn: 'Bedtime Affirmation',
      titleAr: 'توكيد قبل النوم',
      descriptionEn: 'Repeat: "I did my best today, and that is enough"',
      descriptionAr: 'كرر: "بذلت قصارى جهدي اليوم، وهذا يكفي"',
      category: 'evening',
      estimatedMinutes: 2,
      tags: ['positive_thinking', 'self_compassion'],
    ),
  ];
}