// lib/features/progress/domain/entities/daily_activity.dart

class DailyActivity {
  final String id;
  final String titleEn;
  final String titleAr;
  final String descriptionEn;
  final String descriptionAr;
  final String category; // morning, afternoon, evening
  final int estimatedMinutes;
  final List<Tag> tags;

  DailyActivity({
    required this.id,
    required this.titleEn,
    required this.titleAr,
    required this.descriptionEn,
    required this.descriptionAr,
    required this.category,
    required this.estimatedMinutes,
    required this.tags,
  });

  factory DailyActivity.fromMap(Map<String, dynamic> map) {
    return DailyActivity(
      id: map['id'],
      titleEn: map['titleEn'],
      titleAr: map['titleAr'],
      descriptionEn: map['descriptionEn'],
      descriptionAr: map['descriptionAr'],
      category: map['category'],
      estimatedMinutes: map['estimatedMinutes'],
      tags: (map['tags'] as List).map((tag) => Tag.fromMap(tag)).toList(),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'titleEn': titleEn,
      'titleAr': titleAr,
      'descriptionEn': descriptionEn,
      'descriptionAr': descriptionAr,
      'category': category,
      'estimatedMinutes': estimatedMinutes,
      'tags': tags.map((tag) => tag.toMap()).toList(),
    };
  }
}

class Tag {
  final String en;
  final String ar;

  Tag({
    required this.en,
    required this.ar,
  });

  factory Tag.fromMap(Map<String, dynamic> map) {
    return Tag(
      en: map['en'],
      ar: map['ar'],
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'en': en,
      'ar': ar,
    };
  }
}

class DailyActivityRepository {
  List<DailyActivity> getAllActivities() {
    return _allActivities;
  }

  List<DailyActivity> getActivitiesByCategory(String category) {
    return _allActivities.where((activity) => activity.category == category).toList();
  }

  List<DailyActivity> getActivitiesByTags(List<String> tagEnValues) {
    return _allActivities.where((activity) =>
        activity.tags.any((tag) => tagEnValues.contains(tag.en))
    ).toList();
  }

  DailyActivity? getActivityById(String id) {
    try {
      return _allActivities.firstWhere((activity) => activity.id == id);
    } catch (e) {
      return null;
    }
  }

  // Get 3 random activities for today (one from each category)
  List<DailyActivity> getTodaysActivities() {
    final morningActivities = getActivitiesByCategory('morning');
    final afternoonActivities = getActivitiesByCategory('afternoon');
    final eveningActivities = getActivitiesByCategory('evening');

    final random = DateTime.now().microsecondsSinceEpoch;

    return [
      morningActivities[(random % morningActivities.length).toInt()],
      afternoonActivities[(random % afternoonActivities.length).toInt()],
      eveningActivities[(random % eveningActivities.length).toInt()],
    ];
  }

  // 100 IFS-inspired daily activities based on the themes and exercises in
  // No Bad Parts: parts mapping, protector work, unblending, trigger work,
  // Self energy, body awareness, daily IFS meditation, and compassionate review.
  static final List<DailyActivity> _allActivities = [
    DailyActivity(
      id: 'morning_ifs_001',
      titleEn: 'Self Check-In',
      titleAr: 'تفقّد الذات',
      descriptionEn: 'Place one hand on your chest and ask: "How much calm, curiosity, or compassion is available in me right now?" Do not force it. Just notice the quality of your inner space before the day begins.',
      descriptionAr: 'حط إيدك على صدرك واسأل: «قد إيه في هدوء أو فضول أو تعاطف جوايا دلوقتي؟» من غير ضغط. بس لاحظ مساحة جواك قبل اليوم ما يبدأ.',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_002',
      titleEn: 'Meet the Morning Part',
      titleAr: 'قابل جزء الصباح',
      descriptionEn: 'Notice the first strong feeling of the morning. Instead of saying "I am anxious" or "I am tired," try saying: "A part of me feels this." Give that part a little room.',
      descriptionAr: 'لاحظ أول إحساس قوي في الصبح. بدل ما تقول «أنا قلقان» أو «أنا تعبان»، جرّب تقول: «جزء مني حاسس بكده». اديله مساحة بسيطة.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_003',
      titleEn: 'Eight C Breath',
      titleAr: 'نَفَس الثماني صفات',
      descriptionEn: 'Take eight slow breaths. With each breath, invite one quality: calm, curiosity, clarity, compassion, confidence, courage, creativity, and connection. Let the word be enough.',
      descriptionAr: 'خد ٨ أنفاس هادية. مع كل نفس ادعي صفة: الهدوء، الفضول، الوضوح، التعاطف، الثقة، الشجاعة، الإبداع، والاتصال. الكلمة لوحدها كفاية.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'breathing', ar: 'تنفس'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_004',
      titleEn: 'Protector Appreciation',
      titleAr: 'تقدير الحامي',
      descriptionEn: 'Think of a part that tries to keep you organized, perfect, quiet, busy, or safe. Thank it for trying to protect you, even if its way is tiring.',
      descriptionAr: 'افتكر جزء بيحاول يخليك منظم، مثالي، ساكت، مشغول، أو آمن. اشكره لأنه بيحاول يحميك، حتى لو طريقته متعبة.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_005',
      titleEn: 'No Bad Parts Reminder',
      titleAr: 'تذكير لا توجد أجزاء سيئة',
      descriptionEn: 'Start the day by repeating gently: "Every part of me is trying to help in its own way." Let this soften the way you speak to yourself today.',
      descriptionAr: 'ابدأ يومك بجملة لطيفة: «كل جزء جوايا بيحاول يساعد بطريقته». خليها تلين طريقة كلامك مع نفسك النهارده.',
      category: 'morning',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'ifs', ar: 'IFS'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_006',
      titleEn: 'Morning Parts Map',
      titleAr: 'خريطة أجزاء الصباح',
      descriptionEn: 'Draw a small circle for you, then add any parts you notice around it: the planner, critic, tired one, hopeful one, or scared one. No need to solve anything. Just map.',
      descriptionAr: 'ارسم دائرة صغيرة تمثلك، وحط حواليها أي أجزاء حاسس بيها: المخطط، الناقد، المتعب، المتفائل، أو الخائف. مش لازم تحل حاجة. بس ارسم الخريطة.',
      category: 'morning',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'journaling', ar: 'تدوين'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_007',
      titleEn: 'Ask for Space',
      titleAr: 'طلب مساحة',
      descriptionEn: 'Choose one strong part and ask it inside: "Could you give me a little space so I can know you better?" Wait quietly and notice any shift in your body.',
      descriptionAr: 'اختار جزء قوي واسأله جواك: «ممكن تديني مساحة صغيرة عشان أعرفك أكتر؟» استنى بهدوء ولاحظ أي تغير في جسمك.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_008',
      titleEn: 'Curious Morning Question',
      titleAr: 'سؤال فضولي صباحي',
      descriptionEn: 'Ask the part that is most active today: "What are you afraid would happen if you did not do your job?" Write one sentence only.',
      descriptionAr: 'اسأل أكتر جزء نشط النهارده: «إيه اللي خايف يحصل لو ماعملتش شغلك؟» اكتب جملة واحدة بس.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'journaling', ar: 'تدوين'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_009',
      titleEn: 'Inner Weather Report',
      titleAr: 'نشرة الطقس الداخلي',
      descriptionEn: 'Name your inner weather: cloudy, tense, bright, heavy, scattered, or calm. Then ask: "Which part is creating this weather?"',
      descriptionAr: 'سمّي الطقس الداخلي: غائم، مشدود، منوّر، تقيل، مشتت، أو هادي. بعدين اسأل: «أي جزء عامل الطقس ده؟»',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_010',
      titleEn: 'Gentle Witness',
      titleAr: 'الشاهد اللطيف',
      descriptionEn: 'Sit quietly and watch your thoughts like different voices passing by. You do not need to follow them. Practice being the calm witness.',
      descriptionAr: 'اقعد بهدوء وشوف أفكارك كأنها أصوات مختلفة بتعدي. مش لازم تمشي وراها. اتدرب تكون الشاهد الهادي.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_011',
      titleEn: 'Body Doorway',
      titleAr: 'باب الجسد',
      descriptionEn: 'Scan from head to feet and notice one body sensation. Ask: "Does a part of me live here?" Stay kind and curious, not analytical.',
      descriptionAr: 'امسح جسمك من الرأس للقدم ولاحظ إحساس واحد. اسأل: «هل في جزء مني ساكن هنا؟» خليك لطيف وفضولي، مش محلل.',
      category: 'morning',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_012',
      titleEn: 'Fear Needs Care',
      titleAr: 'الخوف يحتاج رعاية',
      descriptionEn: 'If fear appears this morning, imagine turning toward it instead of pushing it away. Say: "I see you. I will not leave you alone."',
      descriptionAr: 'لو الخوف ظهر الصبح، تخيل إنك بتلتفت له بدل ما تزقه بعيد. قول: «أنا شايفك. مش هسيبك لوحدك».',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_013',
      titleEn: 'Critic Softening',
      titleAr: 'تليين الناقد',
      descriptionEn: 'Notice one critical thought. Ask the critic: "What are you trying to prevent?" Thank it for its intention, then choose one kinder sentence.',
      descriptionAr: 'لاحظ فكرة ناقدة واحدة. اسأل الناقد: «إنت بتحاول تمنع إيه؟» اشكره على نيته، واختار جملة ألطف.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_014',
      titleEn: 'Morning Permission',
      titleAr: 'إذن الصباح',
      descriptionEn: 'Give your inner system permission to move slowly today. Say: "We do not have to heal everything today. One gentle step is enough."',
      descriptionAr: 'ادي لنظامك الداخلي إذن يتحرك بهدوء النهارده. قول: «مش لازم نشفي كل حاجة النهارده. خطوة لطيفة واحدة كفاية».',
      category: 'morning',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_015',
      titleEn: 'Planner Dialogue',
      titleAr: 'حوار مع المخطط',
      descriptionEn: 'If a planning part is loud, ask what it wants for you today. Then ask what it needs from you so it can relax a little.',
      descriptionAr: 'لو جزء التخطيط عالي، اسأله هو عايزلك إيه النهارده. بعدين اسأله محتاج منك إيه عشان يهدى شوية.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_016',
      titleEn: 'Morning Boundary',
      titleAr: 'حد صباحي',
      descriptionEn: 'Choose one small boundary for today: a slower reply, a pause before yes, or five minutes alone. Tell your people-pleasing part you are protecting the whole system.',
      descriptionAr: 'اختار حد صغير للنهارده: رد أبطأ، وقفة قبل «نعم»، أو خمس دقائق لوحدك. قول لجزء إرضاء الناس إنك بتحمي النظام كله.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_017',
      titleEn: 'Kind Inner Leader',
      titleAr: 'القائد الداخلي اللطيف',
      descriptionEn: 'Imagine your Self as a steady inner leader. Ask: "How would I guide my parts today if I led with calm instead of pressure?"',
      descriptionAr: 'تخيل ذاتك كقائد داخلي ثابت. اسأل: «هقود أجزائي إزاي النهارده لو قُدت بهدوء بدل الضغط؟»',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_018',
      titleEn: 'Tiny Joy Part',
      titleAr: 'جزء الفرح الصغير',
      descriptionEn: 'Look for a small playful or hopeful part. Ask what tiny joy it wants today: music, color, movement, sunlight, or a kind message.',
      descriptionAr: 'دور على جزء صغير مرح أو متفائل. اسأله عايز فرحة صغيرة إيه النهارده: موسيقى، لون، حركة، شمس، أو رسالة لطيفة.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'creativity', ar: 'إبداع'),
        Tag(en: 'purpose', ar: 'هدف'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_019',
      titleEn: 'Self-Led Intention',
      titleAr: 'نية بقيادة الذات',
      descriptionEn: 'Set one intention using Self energy: "Today I will meet myself with curiosity before judgment." Keep it short and repeat it once.',
      descriptionAr: 'حدد نية من طاقة الذات: «النهارده هقابل نفسي بفضول قبل الحكم». خليها قصيرة وكررها مرة.',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_020',
      titleEn: 'Unblend from Hurry',
      titleAr: 'فصل عن الاستعجال',
      descriptionEn: 'When hurry appears, say: "A part of me feels rushed." Take three slower breaths and ask that part what it is protecting you from.',
      descriptionAr: 'لما الاستعجال يظهر، قول: «جزء مني مستعجل». خد ٣ أنفاس أبطأ واسأل الجزء ده بيحميك من إيه.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'breathing', ar: 'تنفس'),
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_021',
      titleEn: 'Inner Family Roll Call',
      titleAr: 'نداء العائلة الداخلية',
      descriptionEn: 'Name three parts present this morning. Example: the achiever, the sleepy one, the worried one. Welcome each by name without letting one take over.',
      descriptionAr: 'سمّي ٣ أجزاء حاضرة الصبح. مثال: المنجز، النعسان، القلقان. رحّب بكل واحد باسمه من غير ما واحد يسيطر.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_022',
      titleEn: 'Compassionate Mirror',
      titleAr: 'مراية التعاطف',
      descriptionEn: 'Look in the mirror and speak to the part that feels least accepted: "You are welcome here. I want to understand you."',
      descriptionAr: 'بص في المراية واتكلم مع الجزء الأقل قبولًا: «إنت مرحب بيك هنا. أنا عايز أفهمك».',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'exile', ar: 'جزء حساس'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_023',
      titleEn: 'Morning Trigger Preview',
      titleAr: 'استعداد لمحفز اليوم',
      descriptionEn: 'Think of one possible trigger today. Ask your system: "Which part might react? What support would help it feel safer?"',
      descriptionAr: 'افتكر محفز محتمل النهارده. اسأل نظامك: «أي جزء ممكن يتفاعل؟ وإيه الدعم اللي يخليه يحس بأمان أكتر؟»',
      category: 'morning',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_024',
      titleEn: 'Calm Seat Practice',
      titleAr: 'مقعد الهدوء',
      descriptionEn: 'Sit as if you are taking the inner seat of Self. Feel your feet, lengthen your spine, and let your parts know you are here.',
      descriptionAr: 'اقعد كأنك بتاخد مقعد الذات الداخلي. حس برجلك، افرد ضهرك، وخلي أجزائك تعرف إنك موجود.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_025',
      titleEn: 'Ask the Skeptic',
      titleAr: 'اسأل المتشكك',
      descriptionEn: 'If a skeptical part doubts this work, welcome it. Ask: "What are you worried would happen if I trusted this process?"',
      descriptionAr: 'لو جزء متشكك مش مصدق الشغل ده، رحّب بيه. اسأله: «إيه اللي قلقان يحصل لو وثقت في العملية دي؟»',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_026',
      titleEn: 'One Part, One Need',
      titleAr: 'جزء واحد واحتياج واحد',
      descriptionEn: 'Choose one part and write only two words: its feeling and its need. Example: scared / reassurance. Keep it simple.',
      descriptionAr: 'اختار جزء واحد واكتب كلمتين بس: إحساسه واحتياجه. مثال: خائف / طمأنة. خليها بسيطة.',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_027',
      titleEn: 'Morning Inner Thank You',
      titleAr: 'شكر داخلي صباحي',
      descriptionEn: 'Thank three parts for roles they played recently, even if those roles were extreme. Appreciation helps parts soften.',
      descriptionAr: 'اشكر ٣ أجزاء على أدوارهم مؤخرًا، حتى لو كانت أدوار شديدة. التقدير بيساعد الأجزاء تلين.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_028',
      titleEn: 'Self Energy Scan',
      titleAr: 'مسح طاقة الذات',
      descriptionEn: 'Rate from 0 to 10 how much calm, clarity, and compassion you feel. Choose one quality to invite during the day.',
      descriptionAr: 'قيّم من ٠ إلى ١٠ مقدار الهدوء والوضوح والتعاطف عندك. اختار صفة واحدة تدعيها خلال اليوم.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_029',
      titleEn: 'Permission to Pause',
      titleAr: 'إذن بالتوقف',
      descriptionEn: 'Before checking your phone, pause for ten seconds and ask: "Who wants to reach for distraction? What is it helping me avoid?"',
      descriptionAr: 'قبل ما تمسك الموبايل، قف ١٠ ثواني واسأل: «مين عايز يهرب للتشتت؟ وده بيساعدني أتجنب إيه؟»',
      category: 'morning',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_030',
      titleEn: 'Inner Child Greeting',
      titleAr: 'تحية الطفل الداخلي',
      descriptionEn: 'Imagine a younger part of you waking up too. Offer it one sentence of reassurance: "I am older now, and I can be with you."',
      descriptionAr: 'تخيل جزء أصغر منك صاحي معاك. قدم له جملة طمأنة: «أنا كبرت دلوقتي، وأقدر أكون معاك».',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_031',
      titleEn: 'Values from Self',
      titleAr: 'قيم من الذات',
      descriptionEn: 'Ask: "What matters today when I am not led by fear?" Choose one value, like honesty, rest, kindness, or courage.',
      descriptionAr: 'اسأل: «إيه المهم النهارده لما ما أكونش متقاد بالخوف؟» اختار قيمة واحدة زي الصدق، الراحة، اللطف، أو الشجاعة.',
      category: 'morning',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'purpose', ar: 'هدف'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_032',
      titleEn: 'Gentle Start Ritual',
      titleAr: 'طقس بداية لطيف',
      descriptionEn: 'Create a two-minute start ritual: breathe, name one part, and choose one kind action. Repeat it before beginning work or study.',
      descriptionAr: 'اعمل طقس بداية دقيقتين: تنفس، سمّي جزء واحد، واختار فعل لطيف. كرره قبل الشغل أو المذاكرة.',
      category: 'morning',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'breathing', ar: 'تنفس'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_033',
      titleEn: 'Protector Permission',
      titleAr: 'إذن من الحامي',
      descriptionEn: 'Before doing emotional work, ask your protectors if it is okay to go slowly. Respect any no. Safety builds trust.',
      descriptionAr: 'قبل أي عمل عاطفي، اسأل الحماة جواك إذا كان ينفع تمشي ببطء. احترم أي رفض. الأمان بيبني ثقة.',
      category: 'morning',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'morning_ifs_034',
      titleEn: 'Morning Connection',
      titleAr: 'اتصال صباحي',
      descriptionEn: 'Send one gentle message or prayer for connection. Let a lonely part know connection can happen in small, safe steps.',
      descriptionAr: 'ابعت رسالة لطيفة أو دعوة للاتصال. خلي الجزء الوحيد يعرف إن الاتصال ممكن يحصل بخطوات صغيرة وآمنة.',
      category: 'morning',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'connection', ar: 'اتصال'),
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_001',
      titleEn: 'Trigger Trailhead',
      titleAr: 'مدخل المحفز',
      descriptionEn: 'When something upsets you, pause and call it a trailhead. Ask: "What part got activated, and what story did it tell me?"',
      descriptionAr: 'لما حاجة تضايقك، قف واعتبرها مدخل. اسأل: «أي جزء اتفعل؟ وإيه القصة اللي حكاها لي؟»',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_002',
      titleEn: 'Unblend at Noon',
      titleAr: 'فصل وقت الظهر',
      descriptionEn: 'Say slowly: "A part of me is angry/sad/scared, and I am here with it." Notice how the sentence creates space.',
      descriptionAr: 'قول ببطء: «جزء مني غضبان/حزين/خايف، وأنا موجود معاه». لاحظ الجملة بتعمل مساحة إزاي.',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_003',
      titleEn: 'Protector Interview',
      titleAr: 'مقابلة مع الحامي',
      descriptionEn: 'Choose a protective part and ask three questions: What is your job? What are you afraid of? What do you need from me?',
      descriptionAr: 'اختار جزء حامي واسأله ٣ أسئلة: شغلك إيه؟ خايف من إيه؟ محتاج مني إيه؟',
      category: 'afternoon',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_004',
      titleEn: 'Parts Around a Conflict',
      titleAr: 'أجزاء حول الخلاف',
      descriptionEn: 'Think of a current conflict. List the parts involved: the defender, pleaser, scared one, angry one, or avoider. No judgment.',
      descriptionAr: 'افتكر خلاف حالي. اكتب الأجزاء المشتركة: المدافع، المُرضي، الخائف، الغاضب، أو المتجنب. من غير حكم.',
      category: 'afternoon',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'connection', ar: 'اتصال'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_005',
      titleEn: 'Dilemma Meditation',
      titleAr: 'تأمل الحيرة',
      descriptionEn: 'For a decision, identify the part that says yes and the part that says no. Listen to each one separately before choosing.',
      descriptionAr: 'في قرار محير، حدد الجزء اللي بيقول نعم والجزء اللي بيقول لا. اسمع لكل واحد لوحده قبل الاختيار.',
      category: 'afternoon',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_006',
      titleEn: 'Inner Negotiation',
      titleAr: 'تفاوض داخلي',
      descriptionEn: 'If two parts are polarized, ask each what positive outcome it wants for you. Look for the shared intention underneath.',
      descriptionAr: 'لو جزئين متعارضين، اسأل كل واحد عايزلك نتيجة إيجابية إيه. دور على النية المشتركة تحت الخلاف.',
      category: 'afternoon',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_007',
      titleEn: 'Firefighter Pause',
      titleAr: 'وقفة الإطفائي',
      descriptionEn: 'When you want quick relief through scrolling, eating, shutting down, or escaping, ask the soothing part what pain it is trying to put out.',
      descriptionAr: 'لما تحتاج راحة سريعة بسكرول، أكل، انسحاب، أو هروب، اسأل جزء التهدئة هو بيحاول يطفي أي ألم.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_008',
      titleEn: 'Manager Check',
      titleAr: 'تفقّد المدير',
      descriptionEn: 'Notice the part that manages image, productivity, or control. Ask what it believes would happen if it relaxed for one hour.',
      descriptionAr: 'لاحظ الجزء اللي بيدير الصورة، الإنتاجية، أو التحكم. اسأله معتقد إيه هيحصل لو ارتاح ساعة.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'boundaries', ar: 'حدود'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_009',
      titleEn: 'Safe Distance',
      titleAr: 'مسافة آمنة',
      descriptionEn: 'If an emotion feels too big, imagine placing it a few steps away where you can see it without being flooded. Thank the part for giving space.',
      descriptionAr: 'لو إحساس كبير جدًا، تخيله على بعد خطوات بحيث تشوفه من غير ما يغرقك. اشكر الجزء لأنه اداك مساحة.',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_010',
      titleEn: 'Listening Not Fixing',
      titleAr: 'استماع بدون إصلاح',
      descriptionEn: 'Choose one part and listen for two minutes without giving advice. The task is not fixing; it is being present.',
      descriptionAr: 'اختار جزء واسمع له دقيقتين من غير نصيحة. المهمة مش إصلاح؛ المهمة حضور.',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_011',
      titleEn: 'Burden Word',
      titleAr: 'كلمة الحمل',
      descriptionEn: 'Ask a part: "What burden are you carrying?" Write one word like shame, fear, pressure, guilt, or loneliness. Breathe with kindness.',
      descriptionAr: 'اسأل جزء: «إيه الحمل اللي شايله؟» اكتب كلمة واحدة زي عار، خوف، ضغط، ذنب، أو وحدة. تنفس بلطف.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'release', ar: 'تحرر'),
        Tag(en: 'journaling', ar: 'تدوين'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_012',
      titleEn: 'Witness the Exile',
      titleAr: 'مشاهدة الجزء الحساس',
      descriptionEn: 'If a young or hurt feeling appears, do not push it away. Let it know you see it from today, not from the past.',
      descriptionAr: 'لو إحساس صغير أو مجروح ظهر، ماتزقوش بعيد. عرفه إنك شايفه من الحاضر، مش من الماضي.',
      category: 'afternoon',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_013',
      titleEn: 'Self-Led No',
      titleAr: 'لا بقيادة الذات',
      descriptionEn: 'Practice one calm no in your mind. Let your pleasing part know: "Saying no can protect connection, not destroy it."',
      descriptionAr: 'تدرب على «لا» هادية جواك. قول لجزء الإرضاء: «قول لا ممكن يحمي الاتصال، مش يدمره».',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'connection', ar: 'اتصال'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_014',
      titleEn: 'Compassion for Reaction',
      titleAr: 'رحمة مع رد الفعل',
      descriptionEn: 'After reacting strongly, say: "A part took over because it was scared or burdened." Then ask what it needs now.',
      descriptionAr: 'بعد رد فعل قوي، قول: «جزء سيطر لأنه كان خايف أو شايل حمل». بعدين اسأله محتاج إيه دلوقتي.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_015',
      titleEn: 'Parts Timeline',
      titleAr: 'خط زمني للأجزاء',
      descriptionEn: 'Pick one part and ask when it first learned its role. Write any age, memory, or feeling that comes without forcing.',
      descriptionAr: 'اختار جزء واسأله إمتى اتعلم دوره لأول مرة. اكتب أي سن، ذكرى، أو إحساس يطلع من غير ضغط.',
      category: 'afternoon',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_016',
      titleEn: 'Inner Ally Note',
      titleAr: 'رسالة حليف داخلي',
      descriptionEn: 'Write a short note from your Self to a struggling part: "I understand why you do this. I want to help you feel less alone."',
      descriptionAr: 'اكتب رسالة قصيرة من ذاتك لجزء بيعاني: «أنا فاهم ليه بتعمل كده. عايز أساعدك ماتحسش إنك لوحدك».',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'journaling', ar: 'تدوين'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_017',
      titleEn: 'Trigger Body Map',
      titleAr: 'خريطة الجسم وقت المحفز',
      descriptionEn: 'Recall a mild trigger and locate it in your body. Is it tight, hot, heavy, numb, or shaky? Stay gentle.',
      descriptionAr: 'افتكر محفز بسيط وحدد مكانه في جسمك. هل هو شد، حرارة، ثقل، تنميل، أو رعشة؟ خليك لطيف.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_018',
      titleEn: 'One Step Back',
      titleAr: 'خطوة للخلف',
      descriptionEn: 'Before responding to a message, ask: "Which part wants to answer?" Let Self choose the reply, not the most activated part.',
      descriptionAr: 'قبل الرد على رسالة، اسأل: «أي جزء عايز يرد؟» خلي الذات تختار الرد، مش الجزء الأكثر تفاعلًا.',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'connection', ar: 'اتصال'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_019',
      titleEn: 'Permission Slip',
      titleAr: 'تصريح داخلي',
      descriptionEn: 'Write a permission slip for your system: "It is okay to be unfinished, unsure, or learning." Read it slowly.',
      descriptionAr: 'اكتب تصريح لنظامك: «ينفع أكون غير مكتمل، مش متأكد، أو بتعلم». اقرأه ببطء.',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_020',
      titleEn: 'Curious Anger',
      titleAr: 'فضول مع الغضب',
      descriptionEn: 'If anger is present, ask it what boundary or value it is protecting. Thank it before deciding what action is wise.',
      descriptionAr: 'لو الغضب حاضر، اسأله أي حد أو قيمة بيحميها. اشكره قبل ما تقرر التصرف الحكيم.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_021',
      titleEn: 'Shame Unblending',
      titleAr: 'فصل عن العار',
      descriptionEn: 'When shame says "I am bad," change it to "A part of me carries shame." Notice if compassion becomes more possible.',
      descriptionAr: 'لما العار يقول «أنا سيء»، غيّرها إلى «جزء مني شايل عار». لاحظ هل التعاطف بقى أسهل.',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_022',
      titleEn: 'Parts Meeting',
      titleAr: 'اجتماع الأجزاء',
      descriptionEn: 'Imagine a small meeting table inside. Invite only the parts that feel safe to attend. Ask each to speak one sentence.',
      descriptionAr: 'تخيل ترابيزة اجتماع صغيرة جواك. ادعي فقط الأجزاء اللي حاسة بأمان. خلي كل جزء يقول جملة واحدة.',
      category: 'afternoon',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_023',
      titleEn: 'Repair with a Part',
      titleAr: 'إصلاح مع جزء',
      descriptionEn: 'Apologize to a part you have been criticizing. Say: "I was trying to change you before understanding you."',
      descriptionAr: 'اعتذر لجزء كنت بتنتقده. قول: «كنت بحاول أغيرك قبل ما أفهمك».',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_024',
      titleEn: 'Self Energy in Action',
      titleAr: 'طاقة الذات في الفعل',
      descriptionEn: 'Choose one action that expresses calm leadership: drink water, slow down, send an honest reply, or take a walk.',
      descriptionAr: 'اختار فعل يعبر عن قيادة هادئة: اشرب مية، بطّأ، ابعت رد صادق، أو اتمشى.',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'purpose', ar: 'هدف'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_025',
      titleEn: 'Protector Job Description',
      titleAr: 'وصف وظيفة الحامي',
      descriptionEn: 'Write a job description for one protector: title, duties, fears, and what would help it trust Self more.',
      descriptionAr: 'اكتب وصف وظيفة لحامي داخلي: الاسم، المهام، المخاوف، وإيه اللي يخليه يثق في الذات أكتر.',
      category: 'afternoon',
      estimatedMinutes: 9,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_026',
      titleEn: 'Inner Critic Reframe',
      titleAr: 'إعادة فهم الناقد',
      descriptionEn: 'Translate one harsh thought into a protective wish. Example: "Do not fail" may mean "I want you to be safe from shame."',
      descriptionAr: 'ترجم فكرة قاسية إلى رغبة حماية. مثال: «ما تفشلش» قد تعني «عايزك تكون آمن من العار».',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_027',
      titleEn: 'Exile Comfort Object',
      titleAr: 'أمان للجزء الحساس',
      descriptionEn: 'Choose an object nearby as a symbol of safety for a vulnerable part. Hold it and breathe slowly for one minute.',
      descriptionAr: 'اختار شيء قريب كرمز أمان لجزء حساس. امسكه وتنفس ببطء لمدة دقيقة.',
      category: 'afternoon',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_028',
      titleEn: 'From Blame to Burden',
      titleAr: 'من اللوم للحمل',
      descriptionEn: 'When you blame yourself, ask: "What burden is this part carrying that makes it act this way?"',
      descriptionAr: 'لما تلوم نفسك، اسأل: «ما الحمل الذي يحمله هذا الجزء ويخليه يتصرف كده؟»',
      category: 'afternoon',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'ifs', ar: 'IFS'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_029',
      titleEn: 'Connection Check',
      titleAr: 'تفقّد الاتصال',
      descriptionEn: 'Notice whether you feel connected or isolated. Ask the part responsible what kind of safe connection it would accept today.',
      descriptionAr: 'لاحظ هل حاسس باتصال أو عزلة. اسأل الجزء المسؤول يقبل أي نوع اتصال آمن النهارده.',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'connection', ar: 'اتصال'),
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'curiosity', ar: 'فضول'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_030',
      titleEn: 'Small Unburdening Image',
      titleAr: 'صورة تحرر صغيرة',
      descriptionEn: 'Imagine placing one tiny burden, like pressure or guilt, into light, water, earth, or wind. Only release what feels safe.',
      descriptionAr: 'تخيل وضع حمل صغير مثل الضغط أو الذنب في نور، ماء، أرض، أو هواء. حرر فقط ما تشعر أنه آمن.',
      category: 'afternoon',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'release', ar: 'تحرر'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_031',
      titleEn: 'Advanced Map Update',
      titleAr: 'تحديث خريطة متقدم',
      descriptionEn: 'Add arrows between parts on your map: who protects whom, who fights whom, and who needs your Self most today.',
      descriptionAr: 'أضف أسهم بين الأجزاء في خريطتك: مين بيحمي مين، مين بيتعارض مع مين، ومين محتاج ذاتك أكثر اليوم.',
      category: 'afternoon',
      estimatedMinutes: 10,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_032',
      titleEn: 'Midday Self Reset',
      titleAr: 'إعادة ضبط منتصف اليوم',
      descriptionEn: 'Stop for one minute. Feel your feet, soften your jaw, and say: "I can lead from calm for the next small step."',
      descriptionAr: 'قف دقيقة. حس برجلك، ريّح فكك، وقول: «أقدر أقود بهدوء في الخطوة الصغيرة الجاية».',
      category: 'afternoon',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'afternoon_ifs_033',
      titleEn: 'Ask What It Protects',
      titleAr: 'اسأل عما يحميه',
      descriptionEn: 'Choose any habit you dislike and ask the part behind it: "What do you protect me from feeling?"',
      descriptionAr: 'اختار عادة لا تحبها واسأل الجزء وراها: «بتحميني من إحساس إيه؟»',
      category: 'afternoon',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'curiosity', ar: 'فضول'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_001',
      titleEn: 'Daily IFS Meditation',
      titleAr: 'تأمل IFS اليومي',
      descriptionEn: 'Review the day and notice which parts led, which parts hid, and which parts needed you. Thank the system for getting through the day.',
      descriptionAr: 'راجع اليوم ولاحظ أي أجزاء قادت، وأي أجزاء اختفت، وأي أجزاء احتاجتك. اشكر نظامك لأنه عدى اليوم.',
      category: 'evening',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'ifs', ar: 'IFS'),
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_002',
      titleEn: 'Evening Parts Map',
      titleAr: 'خريطة المساء',
      descriptionEn: 'Update your parts map with anything new from today. Circle the part that needs the most kindness tonight.',
      descriptionAr: 'حدّث خريطة الأجزاء بأي شيء جديد من اليوم. حوّط الجزء اللي محتاج أكبر قدر من اللطف الليلة.',
      category: 'evening',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'parts_mapping', ar: 'رسم خريطة الأجزاء'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_003',
      titleEn: 'Unblend Before Sleep',
      titleAr: 'فصل قبل النوم',
      descriptionEn: 'Name one worry as a part: "A part of me is worried about tomorrow." Let it sit beside you instead of inside your whole body.',
      descriptionAr: 'سمّي قلق واحد كجزء: «جزء مني قلقان من بكرة». خليه يقعد جنبك بدل ما يملأ جسمك كله.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_004',
      titleEn: 'Body Meditation',
      titleAr: 'تأمل الجسد',
      descriptionEn: 'Move attention slowly through your body. Wherever you find tension, ask gently: "Is a part holding something here?"',
      descriptionAr: 'حرّك انتباهك ببطء في جسمك. عند أي شد، اسأل بلطف: «هل في جزء شايل حاجة هنا؟»',
      category: 'evening',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_005',
      titleEn: 'Repair the Day',
      titleAr: 'إصلاح اليوم',
      descriptionEn: 'Think of one moment you disliked. Instead of blaming yourself, ask which part took over and what it was trying to do for you.',
      descriptionAr: 'افتكر لحظة لم تعجبك. بدل اللوم، اسأل أي جزء سيطر وماذا كان يحاول أن يفعل لأجلك.',
      category: 'evening',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_006',
      titleEn: 'Thank the Protectors',
      titleAr: 'شكر الحماة',
      descriptionEn: 'Before sleeping, thank the protectors that worked today: the planner, critic, pleaser, avoider, or achiever. Let them know they can rest.',
      descriptionAr: 'قبل النوم، اشكر الحماة اللي اشتغلوا اليوم: المخطط، الناقد، المُرضي، المتجنب، أو المنجز. عرفهم إنهم يقدروا يرتاحوا.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_007',
      titleEn: 'Exile Reassurance',
      titleAr: 'طمأنة الجزء الحساس',
      descriptionEn: 'Speak to a hurt or young part: "You do not have to tell me everything tonight. I am here, and we can go slowly."',
      descriptionAr: 'اتكلم مع جزء مجروح أو صغير: «مش لازم تحكيلي كل حاجة الليلة. أنا هنا، ونقدر نمشي ببطء».',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_008',
      titleEn: 'Let the Inner Critic Rest',
      titleAr: 'راحة للناقد الداخلي',
      descriptionEn: 'If the critic reviews your mistakes, thank it for wanting improvement and ask it to rest until tomorrow.',
      descriptionAr: 'لو الناقد بيراجع أخطاءك، اشكره لأنه يريد التحسن واطلب منه يرتاح لبكرة.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_009',
      titleEn: 'Self-Led Review',
      titleAr: 'مراجعة بقيادة الذات',
      descriptionEn: 'Write three lines: What did a part protect today? What did a part need? What did Self offer?',
      descriptionAr: 'اكتب ٣ سطور: ماذا حمى جزء اليوم؟ ماذا احتاج جزء؟ ماذا قدمت الذات؟',
      category: 'evening',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_010',
      titleEn: 'Safe Place Imagery',
      titleAr: 'صورة مكان آمن',
      descriptionEn: 'Imagine a place where all parts can rest without being forced to talk. Add light, warmth, distance, or a door if needed.',
      descriptionAr: 'تخيل مكان آمن تستطيع فيه كل الأجزاء الراحة بدون إجبار على الكلام. أضف نور، دفء، مسافة، أو باب لو محتاج.',
      category: 'evening',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'sleep', ar: 'نوم'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_011',
      titleEn: 'Release the Day',
      titleAr: 'تحرير اليوم',
      descriptionEn: 'Imagine handing the unfinished parts of the day to the night. Say: "We can return tomorrow with more clarity."',
      descriptionAr: 'تخيل أنك تسلم الأشياء غير المكتملة من اليوم لليل. قول: «نقدر نرجع بكرة بوضوح أكتر».',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'release', ar: 'تحرر'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_012',
      titleEn: 'Lonely Part Care',
      titleAr: 'رعاية الجزء الوحيد',
      descriptionEn: 'If loneliness is present, place a hand on your heart and say: "Your longing makes sense. I will stay with you for a minute."',
      descriptionAr: 'لو الوحدة حاضرة، حط إيدك على قلبك وقول: «اشتياقك مفهوم. هفضل معاك دقيقة».',
      category: 'evening',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'connection', ar: 'اتصال'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_013',
      titleEn: 'Anger Cool Down',
      titleAr: 'تهدئة الغضب',
      descriptionEn: 'Let an angry part know you will not shame it. Ask what boundary it wanted and promise to consider it tomorrow.',
      descriptionAr: 'عرّف الجزء الغاضب أنك لن تخجله. اسأله ما الحد الذي كان يريده ووعده أنك ستفكر فيه غدًا.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_014',
      titleEn: 'Sleep Permission',
      titleAr: 'إذن النوم',
      descriptionEn: 'Tell your busy parts: "Rest is not failure. Rest helps the whole system." Repeat slowly while exhaling.',
      descriptionAr: 'قل لأجزائك المشغولة: «الراحة ليست فشلًا. الراحة تساعد النظام كله». كررها ببطء مع الزفير.',
      category: 'evening',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'breathing', ar: 'تنفس'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_015',
      titleEn: 'Inner Child Bedtime',
      titleAr: 'نوم الطفل الداخلي',
      descriptionEn: 'Imagine tucking in a younger part of you. Offer a blanket, a safe room, or a gentle phrase.',
      descriptionAr: 'تخيل أنك تغطي جزءًا أصغر منك قبل النوم. قدم له بطانية، غرفة آمنة، أو عبارة لطيفة.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'exile', ar: 'جزء حساس'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_016',
      titleEn: 'Parts Gratitude List',
      titleAr: 'قائمة امتنان للأجزاء',
      descriptionEn: 'Write gratitude for three parts: one that protected, one that felt, and one that hoped.',
      descriptionAr: 'اكتب امتنانك لثلاثة أجزاء: جزء حمى، جزء شعر، وجزء كان عنده أمل.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'gratitude', ar: 'امتنان'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'journaling', ar: 'تدوين'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_017',
      titleEn: 'Check the Blenders',
      titleAr: 'تفقّد الأجزاء المسيطرة',
      descriptionEn: 'Ask: "Which part was I blended with most today?" Notice without blame and imagine stepping back from it.',
      descriptionAr: 'اسأل: «أي جزء كنت مندمج معاه أكتر اليوم؟» لاحظ بدون لوم وتخيل أنك ترجع خطوة للخلف منه.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'unblending', ar: 'فصل عن الجزء'),
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_018',
      titleEn: 'Dream Invitation',
      titleAr: 'دعوة للحلم',
      descriptionEn: 'Before sleep, ask your inner system to show you gently what needs attention, only if it feels safe. Keep a notebook nearby.',
      descriptionAr: 'قبل النوم، اطلب من نظامك الداخلي أن يريك بلطف ما يحتاج الانتباه، فقط إذا كان ذلك آمنًا. خلي دفتر قريب.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_019',
      titleEn: 'Forgive a Protector',
      titleAr: 'مسامحة حامٍ',
      descriptionEn: 'Choose a protector that made the day harder. Say: "I know you were trying to help. Let us learn a safer way together."',
      descriptionAr: 'اختار حامي جعل اليوم أصعب. قول: «عارف إنك كنت بتحاول تساعد. خلينا نتعلم طريقة أأمن سوا».',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_020',
      titleEn: 'Quiet System Scan',
      titleAr: 'مسح النظام الهادئ',
      descriptionEn: 'Ask inside: "Does anyone need me before sleep?" Wait. If a part answers, offer attention without opening a deep process.',
      descriptionAr: 'اسأل داخليًا: «هل في حد محتاجني قبل النوم؟» انتظر. لو جزء رد، قدم انتباه بدون فتح عملية عميقة.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_021',
      titleEn: 'Burden Bowl',
      titleAr: 'وعاء الأحمال',
      descriptionEn: 'Imagine a bowl beside your bed. Place today’s pressure, shame, or fear into it for the night. You can pick it up tomorrow if needed.',
      descriptionAr: 'تخيل وعاء بجانب سريرك. ضع فيه ضغط اليوم أو العار أو الخوف لليلة. يمكنك العودة إليه غدًا إذا احتجت.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'release', ar: 'تحرر'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_022',
      titleEn: 'Compassionate Recap',
      titleAr: 'ملخص بتعاطف',
      descriptionEn: 'Retell your day as if every reaction came from a part trying to protect or be heard. Notice how the story softens.',
      descriptionAr: 'احكِ يومك كأن كل رد فعل جاء من جزء يحاول الحماية أو أن يُسمع. لاحظ كيف تلين القصة.',
      category: 'evening',
      estimatedMinutes: 7,
      tags: [
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'reflection', ar: 'تأمل'),
        Tag(en: 'ifs', ar: 'IFS'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_023',
      titleEn: 'Heart to Part',
      titleAr: 'من القلب للجزء',
      descriptionEn: 'Place a hand on your heart and send warmth to one part. No words needed unless they come naturally.',
      descriptionAr: 'حط إيدك على قلبك وابعت دفء لجزء واحد. لا تحتاج كلمات إلا لو جاءت طبيعي.',
      category: 'evening',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'parts_work', ar: 'عمل مع الأجزاء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_024',
      titleEn: 'Tomorrow Support Plan',
      titleAr: 'خطة دعم لبكرة',
      descriptionEn: 'Ask one part what support it needs tomorrow. Write one practical support: time, quiet, food, help, or a boundary.',
      descriptionAr: 'اسأل جزء واحد عن الدعم الذي يحتاجه غدًا. اكتب دعمًا عمليًا: وقت، هدوء، أكل، مساعدة، أو حد.',
      category: 'evening',
      estimatedMinutes: 5,
      tags: [
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'boundaries', ar: 'حدود'),
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_025',
      titleEn: 'Witness Without Story',
      titleAr: 'شاهد بدون قصة',
      descriptionEn: 'For two minutes, feel sensations without explaining them. Let parts know they do not have to perform or justify anything.',
      descriptionAr: 'لمدتين، اشعر بالإحساسات بدون شرح. عرف الأجزاء أنها لا تحتاج أن تثبت أو تبرر أي شيء.',
      category: 'evening',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'calm', ar: 'هدوء'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_026',
      titleEn: 'Connected Self',
      titleAr: 'الذات المتصلة',
      descriptionEn: 'Recall one moment of connection today: with a person, nature, music, prayer, or yourself. Let it fill the body gently.',
      descriptionAr: 'افتكر لحظة اتصال اليوم: مع شخص، طبيعة، موسيقى، دعاء، أو نفسك. خليها تملأ جسمك بلطف.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'connection', ar: 'اتصال'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'gratitude', ar: 'امتنان'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_027',
      titleEn: 'Trailhead Journal',
      titleAr: 'تدوين المدخل',
      descriptionEn: 'Write about one trigger using this format: event, part activated, fear, need, and one Self-led response.',
      descriptionAr: 'اكتب عن محفز واحد بهذا الشكل: الحدث، الجزء المتفعل، الخوف، الاحتياج، ورد بقيادة الذات.',
      category: 'evening',
      estimatedMinutes: 8,
      tags: [
        Tag(en: 'triggers', ar: 'محفزات'),
        Tag(en: 'journaling', ar: 'تدوين'),
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_028',
      titleEn: 'Rest the Achiever',
      titleAr: 'راحة المنجز',
      descriptionEn: 'Tell the achiever part: "You did enough for today." Imagine giving it a chair, tea, or a place to put down its tools.',
      descriptionAr: 'قل لجزء الإنجاز: «عملت كفاية النهارده». تخيل أنك تعطيه كرسي، شاي، أو مكان يضع فيه أدواته.',
      category: 'evening',
      estimatedMinutes: 4,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_029',
      titleEn: 'Gentle Unburdening',
      titleAr: 'تحرر لطيف',
      descriptionEn: 'If a part wants to release something, imagine the burden leaving as smoke, sand, water, or light. Do not push.',
      descriptionAr: 'لو جزء يريد تحرير شيء، تخيل الحمل يخرج كدخان، رمل، ماء، أو نور. لا تضغط.',
      category: 'evening',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'release', ar: 'تحرر'),
        Tag(en: 'body_awareness', ar: 'وعي بالجسد'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_030',
      titleEn: 'Peaceful Inner Room',
      titleAr: 'غرفة داخلية هادئة',
      descriptionEn: 'Build an inner room where protectors can wait safely while you sleep. Add anything they need to trust the rest.',
      descriptionAr: 'ابنِ غرفة داخلية يستطيع الحماة الانتظار فيها بأمان أثناء نومك. أضف ما يحتاجونه للثقة في الراحة.',
      category: 'evening',
      estimatedMinutes: 6,
      tags: [
        Tag(en: 'protector', ar: 'حامٍ داخلي'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_031',
      titleEn: 'Ask for a Dream Guide',
      titleAr: 'طلب مرشد حلم',
      descriptionEn: 'Ask your Self to guide your dreams with calm and clarity. Remind all parts that nothing urgent has to be solved tonight.',
      descriptionAr: 'اطلب من ذاتك أن تقود أحلامك بهدوء ووضوح. ذكّر كل الأجزاء أنه لا يجب حل أي شيء عاجل الليلة.',
      category: 'evening',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'sleep', ar: 'نوم'),
        Tag(en: 'calm', ar: 'هدوء'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_032',
      titleEn: 'Evening Self Promise',
      titleAr: 'وعد الذات المسائي',
      descriptionEn: 'Make one promise you can keep: "Tomorrow I will listen for one minute before judging myself."',
      descriptionAr: 'اعمل وعد تقدر تلتزم به: «بكرة هسمع لنفسي دقيقة قبل ما أحكم عليها».',
      category: 'evening',
      estimatedMinutes: 3,
      tags: [
        Tag(en: 'self_energy', ar: 'طاقة الذات'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'reflection', ar: 'تأمل'),
      ],
    ),
    DailyActivity(
      id: 'evening_ifs_033',
      titleEn: 'Whole System Blessing',
      titleAr: 'بركة للنظام كله',
      descriptionEn: 'End the day by saying: "All parts of me are welcome. We are learning safety, trust, and compassion together."',
      descriptionAr: 'اختم اليوم بقول: «كل أجزائي مرحب بها. نحن نتعلم الأمان والثقة والرحمة معًا».',
      category: 'evening',
      estimatedMinutes: 2,
      tags: [
        Tag(en: 'ifs', ar: 'IFS'),
        Tag(en: 'self_compassion', ar: 'رحمة بالذات'),
        Tag(en: 'sleep', ar: 'نوم'),
      ],
    )
  ];
}
